language: rust
sudo: false
rust:
  - 1.0.0
  - beta
  - nightly
script:
  - cargo build
  - cargo test
  - cargo doc
notifications:
  email: false
  webhooks:
    - https://webhooks.gitter.im/e/295a1e640ebd30d63457
  irc:
    channels:
      - "irc.mozilla.org#winapi"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
