[package]
name = "winapi"
version = "0.3.0-alpha.0"
authors = ["Peter Atashian <retep998@gmail.com>"]
description = "Raw FFI bindings for all of Windows API."
documentation = "https://retep998.github.io/doc/winapi/"
repository = "https://github.com/retep998/winapi-rs"
readme = "README.md"
keywords = ["windows", "ffi", "win32", "com", "directx"]
license = "MIT/Apache-2.0"
include = ["src/**/*", "Cargo.toml", "LICENSE-MIT", "LICENSE-APACHE", "build.rs", "README.md"]
build = "build.rs"

[target.i686-pc-windows-gnu.dependencies]
winapi-i686-pc-windows-gnu = { version = "0.3", path = "i686" }
[target.x86_64-pc-windows-gnu.dependencies]
winapi-x86_64-pc-windows-gnu = { version = "0.3", path = "x86_64" }

[features]
std = []
everything = [ "headers", "libraries" ]
headers = ["headers-shared", "headers-um", "headers-vc"]
"headers-shared" = [
    "shared-basetsd",
    "shared-bcrypt",
    "shared-cderr",
    "shared-cfg",
    "shared-d3d9caps",
    "shared-d3d9types",
    "shared-guiddef",
    "shared-minwindef",
    "shared-ntdef",
    "shared-ntstatus",
    "shared-rpcndr",
    "shared-sspi",
    "shared-windef",
    "shared-windowsx",
    "shared-winerror",
    "shared-wtypesbase",
]
"shared-basetsd" = []
"shared-bcrypt" = ["shared-minwindef", "um-winnt"]
"shared-cderr" = ["shared-minwindef"]
"shared-cfg" = ["um-cfgmgr32"]
"shared-d3d9caps" = ["shared-d3d9types", "shared-guiddef", "shared-minwindef", "um-winnt"]
"shared-d3d9types" = ["shared-basetsd", "shared-guiddef", "shared-minwindef", "um-winnt", "shared-windef"]
"shared-guiddef" = []
"shared-minwindef" = ["shared-basetsd", "shared-ntdef"]
"shared-ntdef" = ["shared-basetsd"]
"shared-ntstatus" = ["shared-ntdef"]
"shared-rpcndr" = []
"shared-sspi" = ["shared-ntdef"]
"shared-windef" = ["shared-minwindef", "um-winnt"]
"shared-windowsx" = ["shared-minwindef"]
"shared-winerror" = ["shared-minwindef"]
"shared-wtypesbase" = ["shared-minwindef", "shared-rpcndr", "um-winnt"]
"headers-um" = [
    "um-cfgmgr32",
    "um-cguid",
    "um-combaseapi",
    "um-consoleapi",
    "um-dbghelp",
    "um-minwinbase",
    "um-ncrypt",
    "um-objidlbase",
    "um-unknwnbase",
    "um-winbase",
    "um-wincon",
    "um-winevt",
    "um-wingdi",
    "um-winnt",
    "um-winreg",
    "um-winuser",
]
"um-cfgmgr32" = ["shared-basetsd", "shared-guiddef", "shared-minwindef", "um-winnt"]
"um-cguid" = ["shared-guiddef"]
"um-combaseapi" = ["shared-basetsd", "shared-minwindef", "shared-wtypesbase", "um-objidlbase", "ole32"]
"um-consoleapi" = ["shared-minwindef", "um-wincon", "um-winnt", "kernel32"]
"um-dbghelp" = ["shared-basetsd","shared-guiddef", "shared-minwindef", "um-winnt", "vc-vcruntime"]
"um-minwinbase" = ["shared-ntstatus"]
"um-ncrypt" = ["shared-basetsd", "shared-sspi", "ncrypt"]
"um-objidlbase" = ["shared-guiddef", "shared-minwindef", "shared-wtypesbase", "um-unknwnbase", "um-winnt"]
"um-unknwnbase" = ["shared-guiddef", "shared-minwindef", "um-winnt"]
"um-winbase" = ["shared-basetsd", "shared-guiddef", "shared-minwindef", "um-cfgmgr32", "um-winnt"]
"um-wincon" = ["shared-minwindef", "shared-windef", "um-minwinbase", "um-wingdi", "um-winnt", "kernel32"]
"um-winevt" = ["shared-minwindef", "um-winnt"]
"um-wingdi" = ["shared-basetsd", "shared-minwindef", "shared-windef", "um-winnt"]
"um-winnt" = ["shared-basetsd", "shared-guiddef", "shared-minwindef", "vc-excpt"]
"um-winreg" = ["shared-basetsd", "shared-minwindef", "um-winnt"]
"um-winuser" = ["shared-basetsd", "shared-minwindef", "shared-windef", "um-wingdi", "um-winnt"]
"headers-vc" = [
    "vc-excpt",
    "vc-vcruntime"
]
"vc-excpt" = []
"vc-vcruntime" = []
libraries = [
    "kernel32",
    "ncrypt",
    "ole32"
]
"kernel32" = []
"ole32" = []
"ncrypt" = []
