[package]
name = "winapi"
version = "0.3.0-dev"
authors = ["Peter Atashian <retep998@gmail.com>"]
description = "Raw FFI bindings for all of Windows API."
documentation = "https://retep998.github.io/doc/winapi/"
repository = "https://github.com/retep998/winapi-rs"
readme = "README.md"
keywords = ["windows", "ffi", "win32", "com", "directx"]
license = "MIT"
include = ["src/**/*", "Cargo.toml", "LICENSE.md"]

[features]
std = []
everything = ["shared.basetsd", "shared.bcrypt", "shared.cderr", "shared.guiddef", "shared.minwindef", "shared.windef", "um.cguid", "um.winnt", "vc.excpt", "vc.vcruntime"]
# Headers
"shared.basetsd" = []
"shared.bcrypt" = ["shared.minwindef", "um.winnt"]
"shared.cderr" = ["shared.minwindef"]
"shared.guiddef" = []
"shared.minwindef" = ["shared.minwindef+um.winnt"]
"shared.windef" = ["shared.minwindef", "um.winnt"]
"um.cguid" = ["shared.guiddef"]
"um.winnt" = ["shared.minwindef+um.winnt"]
"vc.excpt" = []
"vc.vcruntime" = []
# Header cycles
"shared.minwindef+um.winnt" = ["shared.basetsd", "shared.guiddef", "vc.excpt"]
# Libraries
