[package]

name = "winapi"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]
description = "WinAPI FFI bindings. Use this for building higher level abstractions."
repository = "https://github.com/retep998/winapi-rs"
readme = "README.md"
keywords = ["Windows", "win32", "WinAPI", "FFI"]
license = "MIT"

[features]
advapi32 = []
kernel32 = []
ole32 = []
shell32 = []
