[package]
name = "winapi"
version = "0.3.0-dev"
authors = ["Peter Atashian <retep998@gmail.com>"]
description = "Raw FFI bindings for all of Windows API."
documentation = "https://retep998.github.io/doc/winapi/"
repository = "https://github.com/retep998/winapi-rs"
readme = "README.md"
keywords = ["windows", "ffi", "win32", "com", "directx"]
license = "MIT"
include = ["src/**/*", "Cargo.toml", "LICENSE.md"]

[features]
std = []
everything = ["shared.basetsd", "shared.guiddef", "shared.minwindef", "shared.windef", "shared.winnt", "vc.excpt"]
# Headers
"shared.basetsd" = []
"shared.guiddef" = []
"shared.minwindef" = ["shared.minwindef+shared.winnt"]
"shared.windef" = ["shared.minwindef", "shared.winnt"]
"shared.winnt" = ["shared.minwindef+shared.winnt"]
"vc.excpt" = []
# Header cycles
"shared.minwindef+shared.winnt" = ["shared.basetsd", "shared.guiddef"]
# Libraries
